export const CATEGORY_ICON_MAP: Record<string, string> = {
  food: 'ti-tools-kitchen-2',
  dining: 'ti-tools-kitchen-2',
  restaurant: 'ti-tools-kitchen-2',
  meal: 'ti-tools-kitchen-2',
  lunch: 'ti-tools-kitchen-2',
  dinner: 'ti-tools-kitchen-2',
  breakfast: 'ti-tools-kitchen-2',
  groceries: 'ti-shopping-cart',
  grocery: 'ti-shopping-cart',
  supermarket: 'ti-shopping-cart',
  coffee: 'ti-coffee',
  cafe: 'ti-coffee',
  drinks: 'ti-glass-full',
  bar: 'ti-glass-full',
  snacks: 'ti-cookie',
  transport: 'ti-car',
  transportation: 'ti-car',
  commute: 'ti-bus',
  bus: 'ti-bus',
  train: 'ti-train',
  taxi: 'ti-car',
  uber: 'ti-car',
  grab: 'ti-car',
  fuel: 'ti-gas-station',
  gas: 'ti-gas-station',
  parking: 'ti-parking',
  travel: 'ti-plane',
  flight: 'ti-plane',
  airline: 'ti-plane',
  shopping: 'ti-shopping-bag',
  clothes: 'ti-shirt',
  clothing: 'ti-shirt',
  fashion: 'ti-shirt',
  shoes: 'ti-shoe',
  accessories: 'ti-sunglasses',
  bills: 'ti-file-invoice',
  utilities: 'ti-plug',
  electricity: 'ti-bolt',
  water: 'ti-droplet',
  internet: 'ti-wifi',
  wifi: 'ti-wifi',
  phone: 'ti-device-mobile',
  mobile: 'ti-device-mobile',
  subscription: 'ti-repeat',
  subscriptions: 'ti-repeat',
  insurance: 'ti-shield',
  rent: 'ti-building',
  mortgage: 'ti-building',
  health: 'ti-heart-pulse',
  medical: 'ti-stethoscope',
  doctor: 'ti-stethoscope',
  hospital: 'ti-building-hospital',
  medicine: 'ti-pill',
  pharmacy: 'ti-pill',
  gym: 'ti-barbell',
  fitness: 'ti-barbell',
  wellness: 'ti-spa',
  entertainment: 'ti-device-tv',
  movies: 'ti-movie',
  cinema: 'ti-movie',
  games: 'ti-device-gamepad-2',
  gaming: 'ti-device-gamepad-2',
  music: 'ti-music',
  streaming: 'ti-player-play',
  sports: 'ti-ball-football',
  hobby: 'ti-palette',
  education: 'ti-school',
  school: 'ti-school',
  tuition: 'ti-school',
  books: 'ti-book',
  course: 'ti-certificate',
  training: 'ti-certificate',
  personal: 'ti-user',
  haircut: 'ti-scissors',
  salon: 'ti-scissors',
  beauty: 'ti-sparkles',
  grooming: 'ti-sparkles',
  home: 'ti-home',
  house: 'ti-home',
  furniture: 'ti-armchair',
  appliances: 'ti-washing-machine',
  repairs: 'ti-tool',
  maintenance: 'ti-tool',
  cleaning: 'ti-spray',
  business: 'ti-briefcase',
  office: 'ti-briefcase',
  supplies: 'ti-clipboard',
  equipment: 'ti-device-laptop',
  software: 'ti-device-laptop',
  finance: 'ti-coins',
  savings: 'ti-piggy-bank',
  investment: 'ti-trending-up',
  tax: 'ti-receipt',
  bank: 'ti-building-bank',
  gift: 'ti-gift',
  donation: 'ti-heart',
  charity: 'ti-heart',
  pets: 'ti-paw',
  pet: 'ti-paw',
  kids: 'ti-baby-carriage',
  children: 'ti-baby-carriage',
};

export function getCategoryIcon(categoryName: string | null | undefined): string {
  if (!categoryName) return 'ti-tag';
  const key = categoryName.toLowerCase().trim();
  if (CATEGORY_ICON_MAP[key]) return CATEGORY_ICON_MAP[key];
  for (const [keyword, icon] of Object.entries(CATEGORY_ICON_MAP)) {
    if (key.includes(keyword) || keyword.includes(key)) return icon;
  }
  return 'ti-tag';
}

/** Converts a hex color to a low-opacity rgba background */
export function hexToRgba(hex: string, alpha: number): string {
  const r = parseInt(hex.slice(1, 3), 16);
  const g = parseInt(hex.slice(3, 5), 16);
  const b = parseInt(hex.slice(5, 7), 16);
  return `rgba(${r}, ${g}, ${b}, ${alpha})`;
}